# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update
apt_packages:
  - libv8-dev
  - libudunits2-dev
dist: precise
