# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
before_install:
    - sudo rm -rf /etc/apt/sources.list.d/rwky-redis.list
    - sudo add-apt-repository ppa:chris-lea/redis-server -y
apt_packages:
  - libv8-dev
  - libudunits2-dev
dist: precise
